from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, field_validator

from core.config.agent_settings import settings

SOURCE_TOPIC_MAP: dict[str, str] = {
    "0.rag": "rag",
    "1.prompt engineering": "llm-fundamentals",
    "2.knowledge graphs": "knowledge-graphs",
    "ai_engineering": "agentic-ai",
    "3.reinforcement_learning": "ml-ops",
    "general": "agentic-ai",
}

OBSIDIAN_TOPICS = settings.obsidian_vault / "topics"


def resolve_topic(pdf_path: Path) -> str:
    """Return the Obsidian topic slug for a given PDF path.

    Walks the path components to find the first matching source folder name.
    Creates the target topic directory if it does not exist.
    Raises ValueError if no known source folder is found in the path.
    """
    for part in pdf_path.parts:
        slug = SOURCE_TOPIC_MAP.get(part)
        if slug is not None:
            topic_dir = OBSIDIAN_TOPICS / slug
            topic_dir.mkdir(parents=True, exist_ok=True)
            return slug
    raise ValueError(
        f"No known source folder found in path: {pdf_path}. "
        f"Known folders: {list(SOURCE_TOPIC_MAP)}"
    )


class NoteMetadata(BaseModel):
    title: str
    source: str  # "book-chapter" | "paper" | "course" | "article"
    topic: str
    tags: list[str]
    date: str  # ISO date processed, e.g. "2026-04-03"
    relevance: int  # 1–5
    source_file: str  # relative path from DROPBOX_READINGS root
    pages: str  # e.g. "1-23"

    @field_validator("relevance")
    @classmethod
    def relevance_in_range(cls, v: int) -> int:
        if not 1 <= v <= 5:
            raise ValueError(f"relevance must be 1–5, got {v}")
        return v

    @field_validator("source")
    @classmethod
    def source_valid(cls, v: str) -> str:
        allowed = {"book-chapter", "paper", "course", "article"}
        if v not in allowed:
            raise ValueError(f"source must be one of {allowed}, got {v!r}")
        return v


class Note(BaseModel):
    metadata: NoteMetadata
    body: str  # Full markdown body generated by Claude
